---
title: "Movie Catalog Deluxe"
type: "challenge"
description: "Display information pulled from a PostgreSQL database."
visibility: "assign"
tags: "sql, sinatra"
ignore:
- "movie-catalog-deluxe.md"
